controller:
  image: "jenkins/jenkins"
  tag: "lts"

  serviceType: NodePort
  nodePort: 32000

  installPlugins:
    - configuration-as-code:latest
    - git:latest
    - kubernetes:latest
    - job-dsl:latest
    - workflow-aggregator:latest
    - workflow-job:latest
    - docker-workflow:latest

  JCasC:
    defaultConfig: false