controller:
  image: "jenkins/jenkins"
  tag: "lts"

  installPlugins:
    - configuration-as-code:latest
    - git:latest
    - kubernetes:latest
    - job-dsl:latest
    - workflow-aggregator:latest
    - workflow-job:latest

  JCasC:
    defaultConfig: false