jobs:
  - script: >
      pipelineJob('Test Pipeline') {
        definition {
          cps {
            script("""\
            pipeline {
              agent {
                kubernetes {
                  yaml '''
                    apiVersion: v1
                    kind: Pod
                    metadata:
                      labels:
                        purpose: jenkins-agent
                    spec:
                      containers:
                      - name: postgres
                        image: postgres:latest
                        command:
                        - cat
                        tty: true
                    '''
                }
              }
              stages {
                stage('Test Stage') {
                  steps {
                    git 'https://github.com/RenatMir/hello-world.git'
                    container('postgres') {
                      sh 'cat Dockerfile'
                    }
                  }
                }
              }
            }
            """.stripIndent())
            sandbox()
          }
        }
      }