jobs:
  - script: >
        pipelineJob('temp-pipeline') {
          definition {
            cps {
              script('''
                pipeline {
                    agent any
                        stages {
                            stage('Stage 1') {
                                steps {
                                    echo 'Hello World!'
                                }
                            }
                        }
                    }
                }
              '''.stripIndent())
              sandbox()     
            }
          }
        }